#!/usr/bin/env python3
"""RF Shadow Imager - SYNTHETIC DEMO.

Runs the imager interface against a simulated room and a simulated walker.
No radio hardware is used and no measurement is taken. Every number on screen
is generated by the model below.

This exists so the interface can be demonstrated without a live Pi, a
calibrated baseline, or a cooperative room. It is not a measurement, is not
evidence of anything, and is labelled as such on every screen.

For real measurements use imager.py.
"""
import json, math, random, threading, time
from flask import Flask

try:
    import numpy as np
except Exception:
    np = None

GRID = 48
MIN_EV = 1.2

app = Flask(__name__)
LOCK = threading.Lock()
T0 = time.time()

# --- simulated room ------------------------------------------------------
# Eight fictional access points at fixed bearings. The names are invented.
APS = [
    ("de:mo:00:00:01", "HALL-AP",     0.00, -48.0),
    ("de:mo:00:00:02", "KITCHEN-AP",  0.79, -55.0),
    ("de:mo:00:00:03", "NEIGHBOUR-1", 1.57, -71.0),
    ("de:mo:00:00:04", "STUDY-AP",    2.36, -62.0),
    ("de:mo:00:00:05", "GARAGE-AP",   3.14, -58.0),
    ("de:mo:00:00:06", "NEIGHBOUR-2", 3.93, -78.0),
    ("de:mo:00:00:07", "BEDROOM-AP",  4.71, -53.0),
    ("de:mo:00:00:08", "NEIGHBOUR-3", 5.50, -74.0),
]

D = {
    "grid": [], "bearing": 0.0, "rose": [], "conf": 0.0,
    "scans": 0, "links": [], "trail": [], "walker": 0.0,
}


def angdiff(a, b):
    return math.atan2(math.sin(a - b), math.cos(a - b))


def simulate(t):
    """Return per-link shadow evidence for a walker at simulated time t.

    The walker follows a slow figure-of-eight. A link is attenuated in
    proportion to how closely the walker's bearing aligns with it.
    """
    # figure-of-eight bearing sweep
    th = math.sin(t * 0.22) * math.pi + math.sin(t * 0.07) * 0.6
    strength = 3.4 + math.sin(t * 0.5) * 0.9        # how strongly they block
    width = 0.46                                    # angular extent of body

    ev, live = {}, {}
    for bssid, name, bearing, base in APS:
        d = abs(angdiff(th, bearing))
        block = strength * math.exp(-(d ** 2) / (2 * width ** 2))
        noise = random.gauss(0, 0.22)
        z = max(0.0, block + noise)
        ev[bssid] = round(z, 2)
        # a plausible current reading: baseline minus the attenuation
        live[bssid] = round(base - z * 1.9 + random.gauss(0, 0.5), 1)
    return ev, live, th


def image(ev, bearings):
    """Angular blockage likelihood - identical maths to the live imager."""
    active = [(b, e) for b, e in ev.items() if e >= MIN_EV and b in bearings]
    if not active or np is None:
        return [], 0.0, 0.0, []

    BINS = 180
    th = np.linspace(-np.pi, np.pi, BINS, endpoint=False)
    ang = np.zeros(BINS)
    spread = 0.42

    for b, e in active:
        d = np.angle(np.exp(1j * (th - bearings[b])))
        ang += min(e, 6.0) * np.exp(-(d ** 2) / (2 * spread ** 2))

    if ang.max() <= 0:
        return [], 0.0, 0.0, []
    ang = ang / ang.max()

    w = ang / ang.sum()
    R = float(abs((w * np.exp(1j * th)).sum()))
    conf = round(min(1.0, R * min(1.0, len(active) / 3.0)), 3)
    peak = round(float(th[int(np.argmax(ang))]), 4)

    ax = np.linspace(-1.0, 1.0, GRID)
    X, Y = np.meshgrid(ax, ax)
    r = np.sqrt(X ** 2 + Y ** 2)
    a = np.arctan2(Y, X)
    idx = ((a + np.pi) / (2 * np.pi) * BINS).astype(int) % BINS
    field = ang[idx]
    taper = np.exp(-((r - 0.55) ** 2) / (2 * 0.30 ** 2)) * (r < 1.02)
    field = field * taper
    if field.max() > 0:
        field = field / field.max()

    return ((field * 255).astype("uint8").flatten().tolist(), peak, conf,
            [round(float(v), 3) for v in ang])


def worker():
    bearings = {b: br for b, _, br, _ in APS}
    while True:
        t = time.time() - T0
        ev, live, walker = simulate(t)
        grid, peak, conf, rose = image(ev, bearings)
        with LOCK:
            D["grid"] = grid
            D["bearing"] = peak
            D["rose"] = rose
            D["conf"] = conf
            D["scans"] += 1
            D["walker"] = round(walker, 4)
            D["links"] = [[b, n, base, live[b], ev[b], br]
                          for b, n, br, base in APS]
            if conf > 0:
                D["trail"].append({"th": peak, "c": conf})
                D["trail"] = D["trail"][-60:]
        time.sleep(0.35)


@app.route("/api/state")
def state():
    with LOCK:
        return json.dumps({
            "grid": D["grid"], "n": GRID, "bearing": D["bearing"],
            "rose": D["rose"], "conf": D["conf"], "scans": D["scans"],
            "links": D["links"], "trail": D["trail"],
            "walker": D["walker"], "demo": True,
        })


@app.route("/")
def home():
    return PAGE


PAGE = r"""<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>RF Shadow Imager - SYNTHETIC DEMO</title><style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
background:#04060b;color:#d8e3ef;overflow:hidden;height:100vh}
#img{position:fixed;inset:0;width:100%;height:100%}
#stripe{position:fixed;top:0;left:0;right:0;z-index:20;background:#7c2d12;
color:#fed7aa;font-size:.66rem;letter-spacing:.18em;text-align:center;
padding:7px;border-bottom:1px solid #ea580c}
#stripe b{color:#fff}
.ui{position:fixed;z-index:5}
#hdr{top:44px;left:22px;pointer-events:none}
#hdr h1{font-size:1.28rem;font-weight:600}#hdr h1 b{color:#fb923c}
#hdr p{font-size:.55rem;color:#4e5f73;letter-spacing:.22em;margin-top:4px}
#badge{top:46px;right:22px;display:flex;align-items:center;gap:8px;
background:rgba(69,26,3,.9);border:1px solid #ea580c;border-radius:20px;
padding:6px 14px;font-size:.6rem;letter-spacing:.15em;color:#fdba74}
#dot{width:7px;height:7px;border-radius:50%;background:currentColor;
animation:bl 1.6s infinite}@keyframes bl{0%,100%{opacity:1}50%{opacity:.25}}
.card{background:rgba(8,12,20,.85);border:1px solid #161f2c;border-radius:11px;
padding:14px 15px;backdrop-filter:blur(10px)}
.t{font-size:.54rem;color:#4e5f73;letter-spacing:.22em;margin-bottom:10px}
.kv{display:flex;justify-content:space-between;padding:5px 0;font-size:.7rem}
.kv+.kv{border-top:1px solid #101822}
.k{color:#6f8095}.v{color:#fb923c;font-variant-numeric:tabular-nums}
#left{top:108px;left:22px;width:262px}
#right{top:108px;right:22px;width:238px}
.lk{display:flex;justify-content:space-between;align-items:center;
font-size:.63rem;padding:5px 0;border-top:1px solid #101822;color:#7d8fa3}
.lk.hot{color:#fdba74}.lk.hot .e{color:#fb923c;font-weight:600}
.note{font-size:.58rem;color:#46525f;line-height:1.7;margin-top:11px}
.warnbox{background:rgba(69,26,3,.45);border:1px solid #7c2d12;color:#fdba74;
font-size:.6rem;padding:10px 11px;border-radius:8px;line-height:1.6;
margin-top:11px}
#hint{bottom:20px;left:22px;right:22px;font-size:.57rem;color:#3f4c5b;
line-height:1.7;text-align:center;pointer-events:none}
</style></head><body>
<div id="stripe">&#9888; <b>SYNTHETIC DEMO</b> &mdash; NO RADIO HARDWARE IS IN
USE. EVERY VALUE ON THIS SCREEN IS GENERATED BY A SIMULATION.</div>
<canvas id="img"></canvas>

<div class="ui" id="hdr"><h1><b>&pi;</b> RF Shadow Imager</h1>
<p>SIMULATED ROOM &middot; SIMULATED WALKER</p></div>
<div class="ui" id="badge"><span id="dot"></span>DEMO &middot; SYNTHETIC</div>

<div class="ui card" id="left">
<div class="t">SIMULATED LINKS &mdash; z</div>
<div id="links"></div>
<div class="note">Access point names and addresses are invented. Attenuation is
computed from the simulated walker's bearing, not measured.</div>
</div>

<div class="ui card" id="right">
<div class="t">SIMULATED FIELD</div>
<div class="kv"><span class="k">Shadowed links</span><span class="v" id="nh">&mdash;</span></div>
<div class="kv"><span class="k">Blocked bearing</span><span class="v" id="px">&mdash;</span></div>
<div class="kv"><span class="k">True walker bearing</span><span class="v" id="tw">&mdash;</span></div>
<div class="kv"><span class="k">Range</span><span class="v" style="color:#333f4d">not recoverable</span></div>
<div class="kv"><span class="k">Confidence</span><span class="v" id="cf">&mdash;</span></div>
<div class="kv"><span class="k">Frames</span><span class="v" id="sc">&mdash;</span></div>
<div class="warnbox">This is a simulation for interface demonstration. It
proves nothing about sensing performance. Measured results are in
<b>docs/STUDY.md</b>; the live tool is <b>apps/imager.py</b>.</div>
<div class="note">The estimator and rendering are identical to the live tool.
Only the input differs: a generated walker instead of radio measurements.
"True walker bearing" is the simulation's ground truth, which does not exist
in the real system.</div>
</div>

<div id="hint" class="ui">Simulated data &middot; bearing only, no range
&middot; one receiver cannot triangulate</div>

<script>
var c=document.getElementById('img'),x=c.getContext('2d');
var S={grid:[],n:48,bearing:0,rose:[],conf:0,links:[],trail:[],walker:0};
var tick=0;
function id(s){return document.getElementById(s)}
function heat(v){
 var st=[[4,8,20],[12,45,90],[20,120,150],[251,146,60],[253,224,71],[255,255,255]];
 var t=Math.max(0,Math.min(0.999,v))*(st.length-1),i=Math.floor(t),f=t-i;
 var a=st[i],b=st[i+1]||st[i];
 return [a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f,a[2]+(b[2]-a[2])*f];
}
function draw(){
 var W=c.width=c.clientWidth*2,H=c.height=c.clientHeight*2;
 x.clearRect(0,0,W,H);
 var cx=W/2,cy=H/2+30,R=Math.min(W,H)*0.32;
 var N=S.n,gr=S.grid;
 if(gr&&gr.length===N*N){
  var im=x.createImageData(N,N);
  for(var i=0;i<N*N;i++){
   var v=gr[i]/255,co=heat(v);
   im.data[i*4]=co[0];im.data[i*4+1]=co[1];im.data[i*4+2]=co[2];
   im.data[i*4+3]=Math.min(255,36+v*212);
  }
  var off=document.createElement('canvas');off.width=N;off.height=N;
  off.getContext('2d').putImageData(im,0,0);
  x.save();x.globalCompositeOperation='lighter';
  x.drawImage(off,cx-R,cy-R,R*2,R*2);x.restore();
 }
 for(var k=1;k<=4;k++){
  x.beginPath();x.arc(cx,cy,R*k/4,0,6.283);
  x.strokeStyle='rgba(251,146,60,0.08)';x.lineWidth=1.3;x.stroke();
 }
 for(var i2=0;i2<S.links.length;i2++){
  var L=S.links[i2],th=L[5],ev=L[4]||0,hot=ev>=1.2;
  var ax=cx+Math.cos(th)*R,ay=cy+Math.sin(th)*R;
  var g2=x.createLinearGradient(ax,ay,cx,cy);
  g2.addColorStop(0,hot?'rgba(251,146,60,0.45)':'rgba(96,165,250,0.10)');
  g2.addColorStop(1,'rgba(96,165,250,0.02)');
  x.beginPath();x.moveTo(ax,ay);x.lineTo(cx,cy);
  x.strokeStyle=g2;x.lineWidth=hot?Math.min(9,3+ev*1.3):1.6;x.stroke();
  x.beginPath();x.arc(ax,ay,hot?8:5.5,0,6.283);
  x.fillStyle=hot?'#fb923c':'#3b5b82';x.fill();
  x.font='15px ui-monospace,monospace';x.textAlign='center';
  x.fillStyle=hot?'#fdba74':'#5a6f87';
  x.fillText(L[1],ax+Math.cos(th)*40,ay+Math.sin(th)*40+5);
 }
 if(S.rose&&S.rose.length){
  var B=S.rose.length;x.beginPath();
  for(var r2=0;r2<=B;r2++){
   var a3=-Math.PI+(r2%B)/B*2*Math.PI;
   var rad=R*(0.12+S.rose[r2%B]*0.30);
   var qx=cx+Math.cos(a3)*rad,qy=cy+Math.sin(a3)*rad;
   r2?x.lineTo(qx,qy):x.moveTo(qx,qy);
  }
  x.closePath();x.fillStyle='rgba(251,146,60,0.10)';x.fill();
  x.strokeStyle='rgba(251,146,60,0.42)';x.lineWidth=1.8;x.stroke();
 }
 if(S.conf>0){
  var bth=S.bearing,half=0.42*(1.25-S.conf*0.6);
  x.beginPath();x.moveTo(cx,cy);x.arc(cx,cy,R,bth-half,bth+half);
  x.closePath();x.fillStyle='rgba(255,255,255,'+(0.05+S.conf*0.12)+')';x.fill();
  x.beginPath();x.moveTo(cx,cy);
  x.lineTo(cx+Math.cos(bth)*R,cy+Math.sin(bth)*R);
  x.strokeStyle='rgba(255,255,255,'+(0.3+S.conf*0.45)+')';
  x.lineWidth=2.4;x.stroke();
 }
 // simulation ground truth - dashed, does not exist in the real system
 var wt=S.walker;
 x.setLineDash([10,10]);
 x.beginPath();x.moveTo(cx,cy);
 x.lineTo(cx+Math.cos(wt)*R*1.06,cy+Math.sin(wt)*R*1.06);
 x.strokeStyle='rgba(148,163,184,0.5)';x.lineWidth=2;x.stroke();
 x.setLineDash([]);
 var wx=cx+Math.cos(wt)*R*0.72,wy=cy+Math.sin(wt)*R*0.72;
 x.beginPath();x.arc(wx,wy,7,0,6.283);
 x.fillStyle='rgba(203,213,225,0.85)';x.fill();
 x.font='14px ui-monospace,monospace';x.textAlign='center';
 x.fillStyle='rgba(148,163,184,0.7)';
 x.fillText('simulated walker',wx,wy-16);

 x.beginPath();x.arc(cx,cy,10,0,6.283);
 x.fillStyle='#0b1320';x.fill();
 x.strokeStyle='#fb923c';x.lineWidth=2.4;x.stroke();
 x.font='15px ui-monospace,monospace';x.fillStyle='#4e5f73';
 x.fillText('Pi',cx,cy+34);
 tick++;
}
async function poll(){
 try{
  var d=await(await fetch('/api/state')).json();S=d;
  var hot=0,h='';
  for(var k=0;k<d.links.length;k++){
   var L=d.links[k],isHot=L[4]>=1.2;if(isHot)hot++;
   h+='<div class="lk'+(isHot?' hot':'')+'"><span>'+L[1]+'</span>'+
      '<span class="e">'+L[3]+' / '+L[2]+' &middot; z '+
      L[4].toFixed(1)+'</span></div>';
  }
  id('links').innerHTML=h;
  id('nh').textContent=hot+' / '+d.links.length;
  id('px').textContent=d.conf>0?
    (((d.bearing*180/Math.PI)+360)%360).toFixed(0)+'\u00b0':'—';
  id('tw').textContent=(((d.walker*180/Math.PI)+360)%360).toFixed(0)+'\u00b0';
  id('cf').textContent=d.conf.toFixed(2);
  id('sc').textContent=d.scans;
 }catch(e){}
}
function loop(){draw();requestAnimationFrame(loop)}
setInterval(poll,300);poll();loop();
</script></body></html>"""

if __name__ == "__main__":
    threading.Thread(target=worker, daemon=True).start()
    print("\n  *** SYNTHETIC DEMO - no radio hardware in use ***")
    print("  Serving on http://0.0.0.0:5007\n")
    app.run(host="0.0.0.0", port=5007, threaded=True)
